spring:
  application:
    name: mayte
  datasource:
    url: jdbc:mariadb://localhost:3306/mayte
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: lang/messages
  mail:
    host: smtp.example.com
    port: 587
    username: username
    password: password
    protocol: smtp
    ssl:
      enabled: true
cors:
  allowed-origins: [ http://localhost:5173 ]
jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000
